
GET http://localhost:3001/users

###
# Get contact by ID
GET http://localhost:3001/users/668532995066cbc9f60e5908

### Create Contact
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
    "firstName":"Garie",
    "lastName":"Oxezei",
    "email":"garox@gmail.com",
    "favoriteColor":"black",
    "birthday":"24-10-1999"
}

### PUT Contact

PUT http://localhost:3001/users/66853643ef9d2ddaecab4bfd HTTP/1.1
Content-Type: application/json

{
    "firstName":"Jensen",
    "lastName":"Olz",
    "email":"jo@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"24-10-1996"
}

### DELETE Contact

DELETE http://localhost:3000/users/6685384bef9d2ddaecab4c00 HTTP/1.1
Content-Type: application/json

{
    "firstName": null,
    "lastName": null,
    "email": "any",
    "favoriteColor": null,
    "birthday": null
}
